/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ImportantNote {
    title: string;
    featured: boolean;
    content: string;
    subject: string;
    creationTimestamp: Time;
}
export interface Book {
    coverImageUrl?: string;
    title: string;
    subject: string;
    downloadLink: string;
    description: string;
    important: boolean;
    author: string;
}
export type Time = bigint;
export interface Note {
    title: string;
    uploaderName: string;
    subject: string;
    pdfContent?: string;
    description: string;
    uploadTimestamp: Time;
    viewCount: bigint;
    fileContent: string;
    pdfFileName?: string;
}
export interface backendInterface {
    addBook(title: string, author: string, subject: string, description: string, coverImageUrl: string | null, downloadLink: string, important: boolean): Promise<void>;
    addImportantNote(title: string, subject: string, content: string, featured: boolean): Promise<void>;
    addNote(title: string, subject: string, description: string, fileContent: string, uploaderName: string, pdfContent: string | null, pdfFileName: string | null): Promise<void>;
    addViewCount(title: string): Promise<void>;
    deleteNote(title: string): Promise<void>;
    getAllBooks(): Promise<Array<Book>>;
    getAllImportantNotes(): Promise<Array<ImportantNote>>;
    getAllNotes(): Promise<Array<Note>>;
    getBook(title: string): Promise<Book>;
    getFeaturedImportantNotes(): Promise<Array<ImportantNote>>;
    getImportantBooks(): Promise<Array<Book>>;
    getImportantNote(title: string): Promise<ImportantNote>;
    getNote(title: string): Promise<Note>;
    getNotesBySubject(subject: string): Promise<Array<Note>>;
}
import type { Book as _Book, Note as _Note, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBook(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: string, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBook(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBook(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async addImportantNote(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addImportantNote(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addImportantNote(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addNote(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async addViewCount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addViewCount(arg0);
            return result;
        }
    }
    async deleteNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async getAllBooks(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBooks();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBooks();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllImportantNotes(): Promise<Array<ImportantNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllImportantNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllImportantNotes();
            return result;
        }
    }
    async getAllNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBook(arg0: string): Promise<Book> {
        if (this.processError) {
            try {
                const result = await this.actor.getBook(arg0);
                return from_candid_Book_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBook(arg0);
            return from_candid_Book_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedImportantNotes(): Promise<Array<ImportantNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedImportantNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedImportantNotes();
            return result;
        }
    }
    async getImportantBooks(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImportantBooks();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImportantBooks();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImportantNote(arg0: string): Promise<ImportantNote> {
        if (this.processError) {
            try {
                const result = await this.actor.getImportantNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImportantNote(arg0);
            return result;
        }
    }
    async getNote(arg0: string): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return from_candid_Note_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return from_candid_Note_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesBySubject(arg0: string): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesBySubject(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesBySubject(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Book_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Book): Book {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coverImageUrl: [] | [string];
    title: string;
    subject: string;
    downloadLink: string;
    description: string;
    important: boolean;
    author: string;
}): {
    coverImageUrl?: string;
    title: string;
    subject: string;
    downloadLink: string;
    description: string;
    important: boolean;
    author: string;
} {
    return {
        coverImageUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.coverImageUrl)),
        title: value.title,
        subject: value.subject,
        downloadLink: value.downloadLink,
        description: value.description,
        important: value.important,
        author: value.author
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    uploaderName: string;
    subject: string;
    pdfContent: [] | [string];
    description: string;
    uploadTimestamp: _Time;
    viewCount: bigint;
    fileContent: string;
    pdfFileName: [] | [string];
}): {
    title: string;
    uploaderName: string;
    subject: string;
    pdfContent?: string;
    description: string;
    uploadTimestamp: Time;
    viewCount: bigint;
    fileContent: string;
    pdfFileName?: string;
} {
    return {
        title: value.title,
        uploaderName: value.uploaderName,
        subject: value.subject,
        pdfContent: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.pdfContent)),
        description: value.description,
        uploadTimestamp: value.uploadTimestamp,
        viewCount: value.viewCount,
        fileContent: value.fileContent,
        pdfFileName: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.pdfFileName))
    };
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Book>): Array<Book> {
    return value.map((x)=>from_candid_Book_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n7(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
