/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Book = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'pdfBase64' : IDL.Opt(IDL.Text),
  'pdfFileName' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const ImportantNote = IDL.Record({
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'creationTimestamp' : Time,
});
export const Note = IDL.Record({
  'title' : IDL.Text,
  'uploaderName' : IDL.Text,
  'subject' : IDL.Text,
  'pdfContent' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'uploadTimestamp' : Time,
  'viewCount' : IDL.Nat,
  'fileContent' : IDL.Text,
  'pdfFileName' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addBook' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'addImportantNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'addNote' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'addViewCount' : IDL.Func([IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllImportantNotes' : IDL.Func([], [IDL.Vec(ImportantNote)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
  'getFeaturedImportantNotes' : IDL.Func(
      [],
      [IDL.Vec(ImportantNote)],
      ['query'],
    ),
  'getImportantNote' : IDL.Func([IDL.Text], [ImportantNote], ['query']),
  'getNote' : IDL.Func([IDL.Text], [Note], ['query']),
  'getNotesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Book = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'pdfBase64' : IDL.Opt(IDL.Text),
    'pdfFileName' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const ImportantNote = IDL.Record({
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'creationTimestamp' : Time,
  });
  const Note = IDL.Record({
    'title' : IDL.Text,
    'uploaderName' : IDL.Text,
    'subject' : IDL.Text,
    'pdfContent' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'uploadTimestamp' : Time,
    'viewCount' : IDL.Nat,
    'fileContent' : IDL.Text,
    'pdfFileName' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addBook' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'addImportantNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'addNote' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'addViewCount' : IDL.Func([IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllImportantNotes' : IDL.Func([], [IDL.Vec(ImportantNote)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
    'getFeaturedImportantNotes' : IDL.Func(
        [],
        [IDL.Vec(ImportantNote)],
        ['query'],
      ),
    'getImportantNote' : IDL.Func([IDL.Text], [ImportantNote], ['query']),
    'getNote' : IDL.Func([IDL.Text], [Note], ['query']),
    'getNotesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };