/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'coverImageUrl' : [] | [string],
  'title' : string,
  'subject' : string,
  'downloadLink' : string,
  'description' : string,
  'important' : boolean,
  'author' : string,
}
export interface ImportantNote {
  'title' : string,
  'featured' : boolean,
  'content' : string,
  'subject' : string,
  'creationTimestamp' : Time,
}
export interface Note {
  'title' : string,
  'uploaderName' : string,
  'subject' : string,
  'pdfContent' : [] | [string],
  'description' : string,
  'uploadTimestamp' : Time,
  'viewCount' : bigint,
  'fileContent' : string,
  'pdfFileName' : [] | [string],
}
export type Time = bigint;
export interface _SERVICE {
  'addBook' : ActorMethod<
    [string, string, string, string, [] | [string], string, boolean],
    undefined
  >,
  'addImportantNote' : ActorMethod<
    [string, string, string, boolean],
    undefined
  >,
  'addNote' : ActorMethod<
    [string, string, string, string, string, [] | [string], [] | [string]],
    undefined
  >,
  'addViewCount' : ActorMethod<[string], undefined>,
  'deleteNote' : ActorMethod<[string], undefined>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getAllImportantNotes' : ActorMethod<[], Array<ImportantNote>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getBook' : ActorMethod<[string], Book>,
  'getFeaturedImportantNotes' : ActorMethod<[], Array<ImportantNote>>,
  'getImportantBooks' : ActorMethod<[], Array<Book>>,
  'getImportantNote' : ActorMethod<[string], ImportantNote>,
  'getNote' : ActorMethod<[string], Note>,
  'getNotesBySubject' : ActorMethod<[string], Array<Note>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];